openapi: 3.0.0
info:
  title: Student Service REST API
  version: 1.0.0
paths:
  /hello:
    get:
      summary: Returns a greeting message
      operationId: getHello
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello, World!"
servers:
  - url: https://your-choreo-deployment-url
